package logrules

import com.alarm.eagle.util.DateUtil;
import com.alarm.eagle.log.LogEvent;
import org.slf4j.Logger;
import com.alarm.eagle.util.Md5Util;
import com.alarm.eagle.util.RegexUtil
import java.util.Date;

global Logger LOG;

rule "log_app_1 log rules"
    no-loop true
    salience 100
    when
        $log : LogEntry(index == "log_app_1", $msg : message)
    then
        LOG.debug("Receive log_app_1 log, id:[{}]", $log.getId());
        String logTime = RegexUtil.extractString("(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}.\\d{3})", $msg);
        if (logTime == null) {
            LOG.warn("Invalid date or time, log: {}", $msg);
            return;
        }
        Date date = DateUtil.convertFromString("yyyy-MM-dd HH:mm:ss.SSS", logTime);
        $log.setTimestamp(date != null ? date : $log.getAtTimestamp());

        long delayTime = (System.currentTimeMillis() - $log.getTimestamp().getTime())/1000;
        if (delayTime > 5*24*3600 || delayTime < -5*24*3600) {
            LOG.warn("Too early or too late log, ignore it, delay time:{}, log time:{}", delayTime, $log.getTimestamp().getTime());
            return;
        }
        $log.dealDone();
        LOG.debug("out -----log_app_1------");
end